[package]
name = "simple-calculator"
version = "0.1.0"
authors = ["tolga <tolgaparlan@gmail.com>"]
edition = "2018"

[dependencies]
num-bigint = "0.4.3"
num-traits = "0.2.15"
phf = { version = "0.11.1", features = ["macros"] }
thiserror = "1"
